name: Talk2Treasure

on:
  push:
    branches: [ main ]
    
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
       uses: stefanoeb/eslint-action@1.0.2
  prettier:
    runs-on: ubuntu-latest
    steps:
     name: Checkout
     uses: mikeal/publish-to-github-action@master
     run: npm run format
  build:
    runs-on: ubuntu-latest
    steps:
      name: Run Jest
      uses: stefanoeb/jest-action@1.0.3
